class VABs {
    //T1
    MPD_ARROW_C(RPT, MPD_POS_BUTTON_TB_1_X, MPD_POS_BUTTON_T_Y, 3)
    MPD_TEXT_C(RPT,  MPD_POS_BUTTON_TB_1_X, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC("RPT"))
    //T2
    MPD_ARROW_C(ASE, MPD_POS_BUTTON_TB_2_X, MPD_POS_BUTTON_T_Y, 3)
    MPD_TEXT_C(ASE,  MPD_POS_BUTTON_TB_2_X, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC("ASE"))
    //T3
    MPD_ARROW_C(PAN, MPD_POS_BUTTON_TB_3_X-0.025, MPD_POS_BUTTON_T_Y, 3)
    MPD_TEXT_C(PAN,  MPD_POS_BUTTON_TB_3_X-0.025, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC("PAN"))
    //T4
    MPD_TEXT_C(PP, MPD_POS_BUTTON_TB_4_X-0.015, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC(" PP"))
    //T5
    MPD_ARROW_C(COORD, MPD_POS_BUTTON_TB_5_X, MPD_POS_BUTTON_T_Y, 5)
    MPD_TEXT_C(COORD,  MPD_POS_BUTTON_TB_5_X, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC("COORD"))
    //T6
    MPD_ARROW_C(UTIL, MPD_POS_BUTTON_TB_6_X, MPD_POS_BUTTON_T_Y, 4)
    MPD_TEXT_C(UTIL,  MPD_POS_BUTTON_TB_6_X, MPD_POS_BUTTON_T_Y, MPD_TEXT_STATIC("UTIL"))
    //R1
    MPD_TEXT_L(ZOOM_1, MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_1_Y - 2.5 * MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("Z"))
    MPD_TEXT_L(ZOOM_2, MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_1_Y - 1.5 * MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("O"))
    MPD_TEXT_L(ZOOM_3, MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_1_Y - 0.5 * MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("O"))
    MPD_TEXT_L(ZOOM_4, MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_1_Y + 0.5 * MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("M"))
    //R2
    MPD_TEXT_L(SC_Label, MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_2_Y - 0.5 * MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("SC"))
    MPD_BOX_L(SC,        MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_2_Y + 0.5 * MPD_TEXT_HEIGHT, 2)
    MPD_TEXT_L(SC,       MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_2_Y + 0.5 * MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("10"))
    //R3
    MPD_TEXT_L(CTR, MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_3_Y, MPD_TEXT_STATIC("CTR"))
    //R4
    MPD_TEXT_L(CAQ, MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_4_Y, MPD_TEXT_STATIC("CAQ"))
    //R5
    MPD_TEXT_L(FRZ, MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_5_Y, MPD_TEXT_STATIC("FRZ"))
    //R6
    MPD_TEXT_L(ACQ_Label, MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_6_Y - 0.5 * MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("ACQ"))
    MPD_BOX_L(ACQ,        MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_6_Y + 0.5 * MPD_TEXT_HEIGHT, 3)
    MPD_TEXT_L(ACQ,       MPD_POS_BUTTON_R_X, MPD_POS_BUTTON_LR_6_Y + 0.5 * MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("FXD"))
    //B6
    MPD_ARROW_C(THRT, MPD_POS_BUTTON_TB_6_X, MPD_POS_BUTTON_B_Y, 4)
    MPD_TEXT_C(THRT,  MPD_POS_BUTTON_TB_6_X, MPD_POS_BUTTON_B_Y, MPD_TEXT_STATIC("THRT"))
    //B5
    MPD_ARROW_C(RTR, MPD_POS_BUTTON_TB_5_X, MPD_POS_BUTTON_B_Y, 3)
    MPD_TEXT_C(RTE,  MPD_POS_BUTTON_TB_5_X, MPD_POS_BUTTON_B_Y, MPD_TEXT_STATIC("RTE"))
    //B4
    MPD_ARROW_C(WPT, MPD_POS_BUTTON_TB_4_X, MPD_POS_BUTTON_B_Y, 3)
    MPD_TEXT_C(WPT,  MPD_POS_BUTTON_TB_4_X, MPD_POS_BUTTON_B_Y, MPD_TEXT_STATIC(" WPT"))
    //B3
    MPD_ARROW_C(ZN, MPD_POS_BUTTON_TB_3_X-0.015, MPD_POS_BUTTON_B_Y, 2)
    MPD_TEXT_C(ZN,  MPD_POS_BUTTON_TB_3_X-0.015, MPD_POS_BUTTON_B_Y, MPD_TEXT_STATIC("ZN"))
    //L6
    MPD_ARROW_R(SHOW, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_6_Y, 4)
    MPD_TEXT_R(SHOW,  MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_6_Y, MPD_TEXT_STATIC("SHOW"))
    //L4 <-- when a digital message is recieved, this will display in white, future us!
    //MPD_TEXT_L(SHOW, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_4_Y, MPD_TEXT_STATIC("SHOW"))
    //L1
    MPD_ARROW_R(ADF, MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_1_Y, 3)
    MPD_TEXT_R(ADF,  MPD_POS_BUTTON_L_X, MPD_POS_BUTTON_LR_1_Y, MPD_TEXT_STATIC("ADF"))
};

class Boxes {
    type = line;
    width = 3;
    points[] = {
        MPD_POINTS_BOX(Null, 0.15, 0.7, 0.25, 2*MPD_TEXT_HEIGHT), {}, //Waypoint info
        MPD_POINTS_BOX(Null, 0.7, 0.8, 7*MPD_TEXT_WIDTH+0.005, MPD_TEXT_HEIGHT-0.01), {}, //Wind info
        MPD_POINTS_BOX(Null, 0.7+MPD_TEXT_WIDTH, 0.73+0.005, 6*MPD_TEXT_WIDTH, MPD_TEXT_HEIGHT-0.01), {} //Endurance
    };
};

class Occluders {
    color[] = {0,0,0,1};
    class Polygons {
        type = polygon;
        points[] = {
            MPD_POINTS_BOX_POLY(Null, 0.15, 0.7, 0.25, 2*MPD_TEXT_HEIGHT), //Waypoint info
            MPD_POINTS_BOX_POLY(Null, 0.7, 0.8, 7*MPD_TEXT_WIDTH+0.005, MPD_TEXT_HEIGHT-0.01), //Wind info
            MPD_POINTS_BOX_POLY(Null, 0.7+MPD_TEXT_WIDTH, 0.73+0.005, 6*MPD_TEXT_WIDTH, MPD_TEXT_HEIGHT-0.01) //Endurance
        };
    };
};

//Waypoint info
MPD_TEXT_R(WaypointNum, 0.15, 0.7, MPD_TEXT_STATIC("W02"))
MPD_TEXT_R(WaypointGS, 0.15, 0.7+MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("100"))
MPD_TEXT_L(WaypointDist, 0.4, 0.7, MPD_TEXT_STATIC("0.5KM"))
MPD_TEXT_L(WaypointTime, 0.4, 0.7+MPD_TEXT_HEIGHT, MPD_TEXT_STATIC("0:18"))

// Wind info
MPD_TEXT_R(WindInfo, 0.7, 0.8, MPD_TEXT_STATIC("120*/15"))

// Endurance info
MPD_TEXT_L(Endurance, 0.7+7*MPD_TEXT_WIDTH, 0.73, MPD_TEXT_STATIC("2:13"))
MPD_TEXT_SMALL_R(EnduranceLabel, 0.7+MPD_TEXT_WIDTH, 0.73+MPD_TEXT_HEIGHT-MPD_TEXT_SMALL_HEIGHT, MPD_TEXT_STATIC("EN"))
