#define MFD_IND_BATT 0
#define MFD_IND_PAGE_LEFT 1
#define MFD_IND_PAGE_RIGHT 2

#define MFD_IND_UFDTEXT0 0
#define MFD_OFFSET_L 10
#define MFD_OFFSET_R 30

#define MFD_TEXT_IND_FLT_TORQUE  0
#define MFD_TEXT_IND_FLT_AIRSPEED 1
#define MFD_TEXT_IND_FLT_DESTINATION 2
#define MFD_TEXT_IND_FLT_GROUNDSPEED 3
#define MFD_TEXT_IND_FLT_DISTANCETOGO 4
#define MFD_TEXT_IND_FLT_TIMETOGO 5
#define MFD_TEXT_IND_FLT_BALT 6
#define MFD_TEXT_IND_FLT_GALT 7

#define MFD_IND_FLT_TURN 0
#define MFD_IND_FLT_SLIP 1
#define MFD_IND_FLT_COMMAND_HEADING 2
#define MFD_IND_FLT_FCR_CENTERLINE 3
#define MFD_IND_FLT_ALTERNATE_SENSOR 4
#define MFD_IND_FLT_FLY_TO_CUE_X 5
#define MFD_IND_FLT_FLY_TO_CUE_Y 6
#define MFD_IND_FLT_FLIGHT_PATH_X 7
#define MFD_IND_FLT_FLIGHT_PATH_Y 8

#define MFD_TEXT_IND_FUEL_FWD 0
#define MFD_TEXT_IND_FUEL_AFT 1
#define MFD_TEXT_IND_FUEL_INT 2
#define MFD_TEXT_IND_FUEL_ENDR_INT 3
#define MFD_TEXT_IND_FUEL_FLOW_1 4
#define MFD_TEXT_IND_FUEL_FLOW_2 5
#define MFD_TEXT_IND_FUEL_FLOW_TOT 6

#define MPD_PAGE_OFF 0
#define MPD_PAGE_MENU 1
#define MPD_PAGE_FLT 2
#define MPD_PAGE_WCA 3
#define MPD_PAGE_FUEL 4

#define MFD_INDEX_OFFSET(num) (([MFD_OFFSET_R, MFD_OFFSET_L] select _leftSide) + num)