#define MFD_IND_BATT 0
#define MFD_IND_PAGE_LEFT 1
#define MFD_IND_PAGE_RIGHT 2

#define MFD_IND_UFDTEXT0 0
#define MFD_OFFSET_L 10
#define MFD_OFFSET_R 30

#define MFD_IND_FLT_TORQUE 0
#define MFD_IND_FLT_AIRSPEED 1

#define MPD_PAGE_OFF 0
#define MPD_PAGE_MENU 1
#define MPD_PAGE_FLT 2